#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-openmp
#SBATCH -o auto-particle-openmp.stdout
#SBATCH -n 16         
#SBATCH -p RM
#SBATCH -t 00:10:00
#SBATCH -N 1         
     
rm openmp_sum.txt
./serial -n 500 -no -s openmp_sum.txt
./openmp -p 1 -n 500 -no -s openmp_sum.txt
./openmp -p 2 -n 500 -no -s openmp_sum.txt
./openmp -p 4 -n 500 -no -s openmp_sum.txt
./openmp -p 8 -n 500 -no -s openmp_sum.txt
./openmp -p 16 -n 500 -no -s openmp_sum.txt
./openmp -p 2 -n 1000 -no -s openmp_sum.txt
./openmp -p 4 -n 2000 -no -s openmp_sum.txt
./openmp -p 8 -n 4000 -no -s openmp_sum.txt
./openmp -p 16 -n 8000 -no -s openmp_sum.txt
./autograder -v openmp -s openmp_sum.txt
