# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jariy/hw2p1t/hw2p1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jariy/hw2p1t/hw2p1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jariy/hw2p1t/hw2p1/CMakeFiles /home/jariy/hw2p1t/hw2p1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jariy/hw2p1t/hw2p1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named autograder

# Build rule for target.
autograder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autograder
.PHONY : autograder

# fast build rule for target.
autograder/fast:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/build
.PHONY : autograder/fast

#=============================================================================
# Target rules for targets named mpi

# Build rule for target.
mpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi
.PHONY : mpi

# fast build rule for target.
mpi/fast:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/build
.PHONY : mpi/fast

#=============================================================================
# Target rules for targets named openmp

# Build rule for target.
openmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openmp
.PHONY : openmp

# fast build rule for target.
openmp/fast:
	$(MAKE) -f CMakeFiles/openmp.dir/build.make CMakeFiles/openmp.dir/build
.PHONY : openmp/fast

#=============================================================================
# Target rules for targets named serial

# Build rule for target.
serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serial
.PHONY : serial

# fast build rule for target.
serial/fast:
	$(MAKE) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/build
.PHONY : serial/fast

autograder.o: autograder.cpp.o
.PHONY : autograder.o

# target to build an object file
autograder.cpp.o:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/autograder.cpp.o
.PHONY : autograder.cpp.o

autograder.i: autograder.cpp.i
.PHONY : autograder.i

# target to preprocess a source file
autograder.cpp.i:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/autograder.cpp.i
.PHONY : autograder.cpp.i

autograder.s: autograder.cpp.s
.PHONY : autograder.s

# target to generate assembly for a file
autograder.cpp.s:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/autograder.cpp.s
.PHONY : autograder.cpp.s

common.o: common.cpp.o
.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i
.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s
.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/autograder.dir/build.make CMakeFiles/autograder.dir/common.cpp.s
.PHONY : common.cpp.s

mpi.o: mpi.cpp.o
.PHONY : mpi.o

# target to build an object file
mpi.cpp.o:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi.cpp.o
.PHONY : mpi.cpp.o

mpi.i: mpi.cpp.i
.PHONY : mpi.i

# target to preprocess a source file
mpi.cpp.i:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi.cpp.i
.PHONY : mpi.cpp.i

mpi.s: mpi.cpp.s
.PHONY : mpi.s

# target to generate assembly for a file
mpi.cpp.s:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi.cpp.s
.PHONY : mpi.cpp.s

openmp.o: openmp.cpp.o
.PHONY : openmp.o

# target to build an object file
openmp.cpp.o:
	$(MAKE) -f CMakeFiles/openmp.dir/build.make CMakeFiles/openmp.dir/openmp.cpp.o
.PHONY : openmp.cpp.o

openmp.i: openmp.cpp.i
.PHONY : openmp.i

# target to preprocess a source file
openmp.cpp.i:
	$(MAKE) -f CMakeFiles/openmp.dir/build.make CMakeFiles/openmp.dir/openmp.cpp.i
.PHONY : openmp.cpp.i

openmp.s: openmp.cpp.s
.PHONY : openmp.s

# target to generate assembly for a file
openmp.cpp.s:
	$(MAKE) -f CMakeFiles/openmp.dir/build.make CMakeFiles/openmp.dir/openmp.cpp.s
.PHONY : openmp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... autograder"
	@echo "... edit_cache"
	@echo "... mpi"
	@echo "... openmp"
	@echo "... rebuild_cache"
	@echo "... serial"
	@echo "... autograder.o"
	@echo "... autograder.i"
	@echo "... autograder.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... mpi.o"
	@echo "... mpi.i"
	@echo "... mpi.s"
	@echo "... openmp.o"
	@echo "... openmp.i"
	@echo "... openmp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

